# This is a configuration file for the analysis of STROCZECHMDTHolterEK data.
# It includes settings for the file paths, significance level, independent variables,
# and the reference variable to be used in the analysis.
# Ensure that the file paths are correct and accessible.

# File paths
file_path: .\STROCZECHMDTHolterEK_DATA_LABELS_2025-05-21_1136.xlsx
# Output file path for analysis results
save_results: True
save_plots: True
save_path: .\analysis_results
# Significance level for statistical tests
significance_level: 1.0

# Independent variables to be used in the analysis
independent_continuous_variables:
  - BMI
  - Časový odstup od iCMP/TIA
  - Rozměr levé síně
  - Enddiastolický rozměr levé komory (LVEDD)
  - Interventrikulární septum (IVS)
  - Zadní stěna levé komory (Inferolat.)
  - Ejekční frakce levé komory (LVEF)
  - Celkový cholesterol
  - LDL
  - HDL
  - TAG
  - eGFR
  - Sérový kreatinin
  - SVES - počet záznamů 
  - KES - počet záznamů

# Independent categorical variables
independent_binary_variables:
  - Kuřák v době vzniku příznaků iCMP/TIA
  - Abusus alkoholu
  - Osobní anamnéza (choice=Hyperlipidémie)

# Independent categorical variables with multiple categories
reference_var: Záchyt FiS
  