# This is a configuration file for the analysis of STROCZECHMDTHolterEK data.
# It includes settings for the file paths, significance level, independent variables,
# and the reference variable to be used in the analysis.
# Ensure that the file paths are correct and accessible.

# File paths
file_path: .\STROCZECHMDTHolterEK_DATA_LABELS_2025-05-21_1136.xlsx
# Output file path for analysis results
save_results: True
save_plots: True
save_path: .\analysis_results
# Significance level for statistical tests
significance_level: 1.0

variables: .\variables.yaml
  