# ============================================================
# Project  : AFib Risk Factor Correlation Analysis
# File     : config.yaml
# Created on 18. 03. 2026 at 00:00:00
#
# Author: Richard Redina
# Email: 195715@vut.cz
# Affiliation:
#          International Clinical Research Center, Brno
#          Brno University of Technology, Brno
# GitHub: RicRedi
# 
# (._.) 
#  <|>
# _/|_
# 
# Description:
#     Main configuration file for the correlation analysis pipeline.
#     Aggregates settings from analysis, variables, and plotting config files.
#     Ensures that the file paths are correct and accessible.
# ============================================================

# Configuration file for plotting
plotting: ./config/plotting.yaml

# Configuration file for analysis
analysis: ./config/analysis.yaml

# Variables configuration file
variables: ./config/variables.yaml