# Configuration file for hemorrhage analysis

# Independent variables to be used in the analysis
variables:
  - BMI
  - Časový odstup od iCMP/TIA
  - Rozměr levé síně
  - Enddiastolický rozměr levé komory (LVEDD)
  - Interventrikulární septum (IVS)
  - Zadní stěna levé komory (Inferolat.)
  - Ejekční frakce levé komory (LVEF)
  - Celkový cholesterol
  - LDL
  - HDL
  - TAG
  - eGFR
  - Sérový kreatinin
  - SVES - počet záznamů 
  - KES - počet záznamů
  

reference_var:
  - CHA₂DS₂-VASc
  - Antiagregancia (choice=Žádná)
  - Antikoagulancia (choice=Žádná)
  - Závažné krvácivé komplikace během léčby (choice=Žádné)
  - Méně závažné krvácivé komplikace během léčby (choice=Žádné)

conditions:
  cond1:
    col: CHA₂DS₂-VASc
    op: "<="
    value: 4
  cond2:
    col: Antiagregancia (choice=Žádná)
    op: "=="
    value: 1
  cond3:
    col: Antikoagulancia (choice=Žádná)
    op: "=="
    value: 1
  cond4:
    col: Závažné krvácivé komplikace během léčby (choice=Žádné)
    op: "=="
    value: 1
  # cond5:
  #   col: Méně závažné krvácivé komplikace během léčby (choice=Žádné)
  #   op: "=="
  #   value: 1
 
logic: "cond1 & (cond2 | cond3 | cond4 )"

model:
  max_depth: 5
  min_samples_split: 10
  min_samples_leaf: 5
  n_estimators: 100
  random_state: 42

# Output save
output:
  save: true
  save_path: "./results"
  file_format: "json"