# ============================================================
# Project  : AFib Risk Factor Correlation Analysis
# File     : plotting.yaml
# Created on 18. 03. 2026 at 00:00:00
#
# Author: Richard Redina
# Email: 195715@vut.cz
# Affiliation:
#          International Clinical Research Center, Brno
#          Brno University of Technology, Brno
# GitHub: RicRedi
# 
# (._.) 
#  <|>
# _/|_
# 
# Description:
#     Configuration file for visualization settings.
#     Defines output paths, DPI, plot dimensions, and font sizes for correlation plots.
#     Ensure that the file paths are correct and accessible.
# ============================================================

# Saving plots settings
save_plots: True
save_path: ./results/plots
dpi: 300
# Show plots in the notebook or script
show_plots: False
block_plots: False

# Plotting settings
figsize:
  width: 12
  height: 8

# Fontsize settings for plots
fontsize:
  title: 16
  xlabel: 14
  ylabel: 14
  legend: 12
  tick: 12
  tree: 10
