# Configuration file for correlation analysis

# Independent variables to be used in the analysis
independent_continuous_variables:
  - BMI
  - Časový odstup od iCMP/TIA
  - Rozměr levé síně
  - Enddiastolický rozměr levé komory (LVEDD)
  - Interventrikulární septum (IVS)
  - Zadní stěna levé komory (Inferolat.)
  - Ejekční frakce levé komory (LVEF)
  - Celkový cholesterol
  - LDL
  - HDL
  - TAG
  - eGFR
  - Sérový kreatinin
  - SVES - počet záznamů 
  - KES - počet záznamů

# Independent categorical variables
independent_binary_variables:
  - Kuřák v době vzniku příznaků iCMP/TIA
  - Abusus alkoholu
  - Osobní anamnéza (choice=Hyperlipidémie)

# Independent categorical variables with multiple categories
reference_var: Záchyt FiS